# Created by trellis-cli vcanary
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  sweetteamurders.com:
    site_hosts:
    - canonical: sweetteamurders.test
      redirects:
      - www.sweetteamurders.test
    local_path: ../site
    admin_email: admin@sweetteamurders.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
